apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: minecore
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
    name: service
  type: ClusterIP
